name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      TELNYX_MOCK_VERSION: 0.8.13
      TELNYX_MOCK_OPEN_API_URI: https://raw.githubusercontent.com/team-telnyx/openapi/master/openapi/spec3.json
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'
    - name: setup-telnyx-mock
      run: source ./.github/scripts/before_install.sh
    - name: Restore dependencies
      run: dotnet restore ./src/Telnyx.net.sln
    - name: Build
      run: dotnet build ./src/Telnyx.net.sln /clp:ErrorsOnly
    - name: Test
      run: dotnet test ./src/TelnyxTests/TelnyxTests.csproj --configuration Release /clp:ErrorsOnly
